# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2016-07-15 15:19+Mitteleuropäische Sommerzeit\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: ENCODING\n"
"Generated-By: pygettext.py 1.5\n"


#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:65
msgid "Update failed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:65
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4170
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4181
msgid "Could not connect to %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:254
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:256
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:258
msgid "Operating System not supported: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:273
msgid "Copy old appdata to new folder failed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:273
msgid "Error: def win_pre1_check_app_dir()"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:284
msgid "Could not create app_dir: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:306
msgid "Select User-ID failed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:369
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:372
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:375
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:378
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:381
msgid "Error: '%s' not found!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:398
msgid ""
"Could not remove lock file.\n"
"File itself locked because another oVPN Client instance running?"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:449
msgid ""
"Creating API-DIRS\n"
"%s \n"
"%s \n"
"%s \n"
"%s \n"
"%s failed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:451
msgid "Creating config Folders failed"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:669
msgid "Error: def read_options_file"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:669
msgid "Read config file failed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:797
msgid ""
"Error reading your Interfaces from netsh.exe. Contact support@ovpn.to with Error-ID:\n"
"ADAPTERS[1]=(%s)\n"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:832
msgid "Could not read your Network Interfaces! Please install OpenVPN or check if your TAP-Adapter is really enabled and driver installed."
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:863
msgid "No OpenVPN TAP-Windows Adapter found!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:877
msgid ""
"Multiple TAPs found!\n"
"\n"
"Please select your TAP Adapter!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:893
msgid ""
"No OpenVPN TAP-Adapter found!\n"
"Please install openVPN!\n"
"URL1: %s\n"
"URL2: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:898
msgid "Invalid characters in '%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:914
msgid "Choose your External Network Adapter!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:932
msgid "No Network Adapter found!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:947
msgid "Please select your User-ID!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1073
msgid "Disconnect %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1077
msgid "Connect to %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1085
msgid "Remove AutoConnect: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1089
msgid "Set AutoConnect: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1104
msgid "[enabled]"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1106
msgid "[disabled]"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1107
msgid "Load extended Server-View %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1120
msgid "Set Server-View Size [%sx%s]"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1127
msgid "Update every: %s seconds"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1147
msgid "Change DNS"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1154
msgid "Primary DNS: %s (%s)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1164
msgid "Secondary DNS: %s (%s)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1197
msgid "Primary DNS '%s' @ %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1200
msgid "Set Primary DNS"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1206
msgid "Secondary DNS '%s' @ %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1209
msgid "Set Secondary DNS"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1319
msgid "Checking for Updates!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1322
msgid "Disconnected! Have a nice and anonymous day!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1336
msgid "Connecting to %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1342
msgid "Testing connection to %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1357
msgid "Connected to %s [%s]:%s (%s) [ %s ] (%s / %s ms)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1498
msgid "Options"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1505
msgid "Select Network Adapter"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1521
msgid "IPv6 Options"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1525
msgid "Select: IPv4 Entry Server with Exit to IPv4 (standard)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1529
msgid "Select: IPv4 Entry Server with Exits to IPv4 + IPv6"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1547
msgid "Firewall"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1553
msgid "Restore Firewall Backups"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1575
msgid "Updates"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1579
msgid "Normal Config Update"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1583
msgid "Forced Config Update"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1593
msgid "Reset API Login"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1598
msgid "Clear Passphrase from RAM"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1602
msgid "Clear Passphrase from CFG"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1663
msgid " [ disconnect ]"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1706
msgid "Close Servers"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1709
msgid "Servers"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1719
msgid "Close Account"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1721
msgid "Account"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1731
msgid "Close Settings"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1733
msgid "Settings"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1744
msgid "About"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1752
msgid "Quit"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1794
msgid "oVPN Server Update"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1841
msgid "Certificates and Configs updated!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1841
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1854
msgid "oVPN Update OK!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1844
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1846
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1849
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1851
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1857
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1859
msgid "Error: def inThread_timer_check_certdl"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1844
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1846
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1849
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1851
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1857
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1859
msgid "oVPN Update failed"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1854
msgid "No update needed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2104
msgid "oVPN Server - %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2176
msgid "oVPN Server [ %s ]"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2312
msgid "oVPN Account - %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2332
msgid "Settings -> Updates: 'Load Account Info' [disabled]"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2334
msgid "No data loaded! Retry in few seconds..."
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2431
msgid "oVPN Settings - %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2439
msgid ""
"Security Settings\n"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2448
msgid " Security "
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2455
msgid ""
"Options\n"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2461
msgid " Options "
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2490
msgid "Use Windows Firewall (default: ON) "
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2520
msgid "TAP-Adapter block outbound (default: OFF)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2551
msgid "Block Internet on Disconnect or Quit (default: ON)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2579
msgid "Disable FW question on Quit (default: ON)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2607
msgid "Clear Rules on Connect (default: OFF)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2627
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2657
msgid "Could not export Windows Firewall Backup!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2627
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2657
msgid "Error: Windows Firewall Backup failed"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2637
msgid "Backup on Start / Restore on Quit (default: OFF)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2667
msgid "DNS Leak Protection (default: ON)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2696
msgid "Disable '%s' on Disconnect (default: OFF)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2724
msgid "Update Configs on Start (default: OFF)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2749
msgid "Load Account Info (default: OFF)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2784
msgid "Load Server Info (default: OFF)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2822
msgid "Debug Mode (default: OFF)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2838
msgid "Debug Mode Enabled"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2838
msgid ""
"Logfile:\n"
"'%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2849
msgid "Change App Theme"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3172
msgid "Error: Certs not found!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3172
msgid "Files missing: '%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3198
msgid "Could not start Windows Firewall!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3198
msgid "Error: def inThread_spawn_openvpn_process"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3504
msgid "Error: DNS restore 2nd"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3504
msgid "Error: Restore Secondary DNS to %s failed."
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3507
msgid "Error: DNS restore 1st"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3507
msgid "Error: Restore Primary DNS to %s failed."
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3570
msgid "def win_netsh_read_dns_to_backup: failed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3603
msgid ""
"Error:\n"
"SSL Root Certificate for %s not loaded %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3603
msgid "Error: SSL CA Cert #1"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3606
msgid ""
"Error:\n"
"Invalid SSL Root Certificate for %s in:\n"
"'%s'\n"
"hash is:\n"
"'%s'\n"
"but should be '%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3606
msgid "Error: SSL CA Cert #2"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3609
msgid ""
"Error:\n"
"SSL Root Certificate for %s not found in:\n"
"'%s'!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3609
msgid "Error: SSL CA Cert #3"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3798
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3822
msgid "Error: netsh.exe not found!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3837
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3861
msgid "Error: route.exe not found!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3877
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3889
msgid "ipconfig.exe not found!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3929
msgid "Enter your Passphrase"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3934
msgid "Save Passphrase in File?"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3940
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4010
msgid "Passphrase:"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3988
msgid "oVPN.to Setup"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3989
msgid "Enter your oVPN.to Details"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3996
msgid "User-ID:"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4003
msgid "API-Key:"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4009
msgid ""
"\n"
"\n"
"Enter a secure passphrase to encrypt your API-Login!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4016
msgid "Repeat:"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4170
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4181
msgid "Error: Update failed"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4227
msgid "Server Window Size"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4231
msgid "Width (pixel):"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4235
msgid "Height (pixel):"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4239
msgid ""
"Enter width and height\n"
"\n"
"Leave blank for default"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4286
msgid "Load Data every X seconds"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4290
msgid "seconds:"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4339
msgid "Switched to IPv4+6"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4339
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4358
msgid ""
"Changed Option:\n"
"\n"
"Use 'Forced Config Update' to get new configs!\n"
"\n"
"You have to join 'IPv6 Beta' on https://%s to use any IPv6 options!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4358
msgid "Switched to IPv6+4"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4464
msgid "API requests on: %s failed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4464
msgid "Error: def API_REQUEST"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4476
msgid "Invalid User-ID / API-Key or Account expired."
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4579
msgid "Error: def move_appdata"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4579
msgid "Move Userdata to new folder: '%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4615
msgid "Could not read Servers Remote-IP:Port from config: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4624
msgid "Could not read Servers Protocol from config: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4636
msgid "Could not read Servers Cipher from config: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4662
msgid "Error: def load_ovpn_server"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4662
msgid "Load openVPN Server failed"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4836
msgid "Platform '%s' not supported"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4836
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4887
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4891
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4975
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5028
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5031
msgid "Error!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4852
msgid ""
"openVPN Setup downloaded and hash verified OK!\n"
"\n"
"Please start setup from file:\n"
"'%s'\n"
"\n"
"Verify GPG with:\n"
"'%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4854
msgid ""
"openVPN Setup downloaded but hash verify failed!\n"
"Please install openVPN!\n"
"URL1: %s\n"
"URL2: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4861
msgid ""
"Install OpenVPN %s (%s) (%s)\n"
"\n"
"Starting download (~1.8 MB) from:\n"
"'%s'\n"
"to\n"
"'%s'\n"
"\n"
"Please wait..."
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4861
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4927
msgid "Setup: openVPN"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4887
msgid ""
"Invalid File hash: %s !\n"
"localhash = '%s'\n"
"but should be = '%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4891
msgid "Failed remove file: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4927
msgid ""
"OpenVPN not found!\n"
"\n"
"Please select openvpn.exe on next window!\n"
"\n"
"If you did not install openVPN yet: click cancel on next window!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4928
msgid "Select openvpn.exe or Cancel to install openVPN"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4975
msgid ""
"WARNING! Failed to verify files in\n"
"'%s'\n"
"\n"
"Uninstall openVPN and restart oVPN Client Software!\n"
"\n"
"Or install openVPN from URL:\n"
"%s[debug self.LAST_FAILED_CHECKFILE = '%s']"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4980
msgid "Could not detect openVPN Version!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5004
msgid "Could not find openVPN"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5028
msgid "Invalid Hash: '%s'! is '%s' != '%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5031
msgid "Invalid content '%s' in '%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5048
msgid "arch '%s' not supported!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5249
msgid "Quit oVPN.to Client"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5253
msgid "Do you really want to quit?"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5319
msgid "Firewall Settings"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5323
msgid ""
"Restore previous firewall settings?\n"
"\n"
"Press 'YES' to restore your previous firewall settings!\n"
"Press 'NO' to set profiles to 'blockinbound,blockoutbound'!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5326
msgid ""
"Allow outgoing connection to internet?\n"
"\n"
"Press 'YES' to set profiles to 'blockinbound,allowoutbound'!\n"
"Press 'NO' to set profiles to 'blockinbound,blockoutbound'!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5379
msgid "Error"
msgstr ""

