# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2016-07-14 21:28+Mitteleuropäische Sommerzeit\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: ENCODING\n"
"Generated-By: pygettext.py 1.5\n"


#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:65
msgid "Update failed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:65
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4065
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4075
msgid "Could not connect to %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:255
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:257
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:259
msgid "Operating System not supported: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:274
msgid "Copy old appdata to new folder failed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:274
msgid "Error: def win_pre1_check_app_dir()"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:285
msgid "Could not create app_dir: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:307
msgid "Select User-ID failed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:370
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:373
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:376
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:379
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:382
msgid "Error: '%s' not found!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:399
msgid ""
"Could not remove lock file.\n"
"File itself locked because another oVPN Client instance running?"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:450
msgid ""
"Creating API-DIRS\n"
"%s \n"
"%s \n"
"%s \n"
"%s \n"
"%s failed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:452
msgid "Creating config Folders failed"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:662
msgid "Error: def read_options_file"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:662
msgid "Read config file failed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:788
msgid ""
"Error reading your Interfaces from netsh.exe. Contact support@ovpn.to with Error-ID:\n"
"ADAPTERS[1]=(%s)\n"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:823
msgid "Could not read your Network Interfaces! Please install OpenVPN or check if your TAP-Adapter is really enabled and driver installed."
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:854
msgid "No OpenVPN TAP-Windows Adapter found!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:868
msgid ""
"Multiple TAPs found!\n"
"\n"
"Please select your TAP Adapter!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:884
msgid ""
"No OpenVPN TAP-Adapter found!\n"
"Please install openVPN!\n"
"URL1: %s\n"
"URL2: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:889
msgid "Invalid characters in '%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:905
msgid "Choose your External Network Adapter!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:923
msgid "No Network Adapter found!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:938
msgid "Please select your User-ID!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1048
msgid "Choose App Theme"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1088
msgid "Disconnect %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1092
msgid "Connect to %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1100
msgid "Remove AutoConnect: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1104
msgid "Set AutoConnect: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1119
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1511
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1608
msgid "[enabled]"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1121
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1513
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1610
msgid "[disabled]"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1122
msgid "Load extended Server-View %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1135
msgid "Set Server-View Size [%sx%s]"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1144
msgid "Refresh Window"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1162
msgid "Change DNS"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1169
msgid "Primary DNS: %s (%s)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1179
msgid "Secondary DNS: %s (%s)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1212
msgid "Primary DNS '%s' @ %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1215
msgid "Set Primary DNS"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1221
msgid "Secondary DNS '%s' @ %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1224
msgid "Set Secondary DNS"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1316
msgid "Checking for Updates!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1319
msgid "Disconnected! Have a nice and anonymous day!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1333
msgid "Connecting to %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1339
msgid "Testing connection to %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1354
msgid "Connected to %s [%s]:%s (%s) [ %s ] (%s / %s ms)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1495
msgid "Options"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1502
msgid "Select Network Adapter"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1514
msgid "DEBUG Mode %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1523
msgid "Set App Theme [%s]"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1535
msgid "IPv6 Options"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1539
msgid "Select: IPv4 Entry Server with Exit to IPv4 (standard)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1543
msgid "Select: IPv4 Entry Server with Exits to IPv4 + IPv6"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1561
msgid "Firewall"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1567
msgid "Restore Firewall Backups"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1589
msgid "Updates"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1593
msgid "Normal Config Update"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1597
msgid "Forced Config Update"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1611
msgid "Load Account Info %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1621
msgid "Reset API Login"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1626
msgid "Clear Passphrase from RAM"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1630
msgid "Clear Passphrase from CFG"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1691
msgid " [ disconnect ]"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1734
msgid "Close Servers"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1737
msgid "Servers"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1747
msgid "Close Account"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1749
msgid "Account"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1759
msgid "Close Settings"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1761
msgid "Settings"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1772
msgid "About"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1780
msgid "Quit"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1822
msgid "oVPN Server Update"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1869
msgid "Certificates and Configs updated!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1869
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1882
msgid "oVPN Update OK!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1872
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1874
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1877
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1879
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1885
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1887
msgid "Error: def inThread_timer_check_certdl"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1872
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1874
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1877
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1879
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1885
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1887
msgid "oVPN Update failed"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1882
msgid "No update needed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2131
msgid "oVPN Server - %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2203
msgid "oVPN Server [ %s ]"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2338
msgid "oVPN Account - %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2358
msgid "Systray Menu -> Updates -> 'Load Account Info' [disabled]"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2360
msgid "No data loaded! Retry in few seconds..."
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2457
msgid "oVPN Settings - %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2465
msgid ""
"Windows Firewall Settings\n"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2472
msgid " Firewall "
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2479
msgid ""
"Network Adapter Settings\n"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2482
msgid " Network "
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2489
msgid ""
"Update Settings\n"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2491
msgid " Updates "
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2509
msgid "Use Windows Firewall (default: ON) "
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2539
msgid "TAP-Adapter block outbound (default: OFF)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2570
msgid "Block Internet on Disconnect or Quit (default: ON)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2598
msgid "Disable FW question on Quit (default: ON)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2626
msgid "Clear Rules on Connect (default: OFF)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2646
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2676
msgid "Could not export Windows Firewall Backup!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2646
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2676
msgid "Error: Windows Firewall Backup failed"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2656
msgid "Backup on Start / Restore on Quit (default: OFF)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2686
msgid "DNS Leak Protection (default: ON)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2715
msgid "Disable '%s' on Disconnect (default: OFF)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2743
msgid "Update Configs on Start (default: OFF)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3058
msgid "Error: Certs not found!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3058
msgid "Files missing: '%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3084
msgid "Could not start Windows Firewall!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3084
msgid "Error: def inThread_spawn_openvpn_process"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3390
msgid "Error: DNS restore 2nd"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3390
msgid "Error: Restore Secondary DNS to %s failed."
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3393
msgid "Error: DNS restore 1st"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3393
msgid "Error: Restore Primary DNS to %s failed."
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3456
msgid "def win_netsh_read_dns_to_backup: failed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3489
msgid ""
"Error:\n"
"SSL Root Certificate for %s not loaded %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3489
msgid "Error: SSL CA Cert #1"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3492
msgid ""
"Error:\n"
"Invalid SSL Root Certificate for %s in:\n"
"'%s'\n"
"hash is:\n"
"'%s'\n"
"but should be '%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3492
msgid "Error: SSL CA Cert #2"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3495
msgid ""
"Error:\n"
"SSL Root Certificate for %s not found in:\n"
"'%s'!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3495
msgid "Error: SSL CA Cert #3"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3684
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3708
msgid "Error: netsh.exe not found!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3723
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3747
msgid "Error: route.exe not found!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3763
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3775
msgid "ipconfig.exe not found!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3811
msgid "Enter your Passphrase"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3816
msgid "Save Passphrase in File?"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3822
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3898
msgid "Passphrase:"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3876
msgid "oVPN.to Setup"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3877
msgid "Enter your oVPN.to Details"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3884
msgid "User-ID:"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3891
msgid "API-Key:"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3897
msgid ""
"\n"
"\n"
"Enter a secure passphrase to encrypt your API-Login!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3904
msgid "Repeat:"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4016
msgid "Debug Mode Enabled"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4016
msgid ""
"Logfile:\n"
"'%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4065
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4075
msgid "Error: Update failed"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4118
msgid "Server Window Size"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4122
msgid "Width (pixel):"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4126
msgid "Height (pixel):"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4130
msgid ""
"Enter width and height\n"
"\n"
"Leave blank for default"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4186
msgid "Switched to IPv4+6"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4186
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4204
msgid ""
"Changed Option:\n"
"\n"
"Use 'Forced Config Update' to get new configs!\n"
"\n"
"You have to join 'IPv6 Beta' on https://%s to use any IPv6 options!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4204
msgid "Switched to IPv6+4"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4308
msgid "API requests on: %s failed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4308
msgid "Error: def API_REQUEST"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4320
msgid "Invalid User-ID / API-Key or Account expired."
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4420
msgid "Error: def move_appdata"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4420
msgid "Move Userdata to new folder: '%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4456
msgid "Could not read Servers Remote-IP:Port from config: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4465
msgid "Could not read Servers Protocol from config: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4477
msgid "Could not read Servers Cipher from config: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4503
msgid "Error: def load_ovpn_server"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4503
msgid "Load openVPN Server failed"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4675
msgid "Platform '%s' not supported"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4675
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4726
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4730
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4814
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4867
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4870
msgid "Error!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4691
msgid ""
"openVPN Setup downloaded and hash verified OK!\n"
"\n"
"Please start setup from file:\n"
"'%s'\n"
"\n"
"Verify GPG with:\n"
"'%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4693
msgid ""
"openVPN Setup downloaded but hash verify failed!\n"
"Please install openVPN!\n"
"URL1: %s\n"
"URL2: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4700
msgid ""
"Install OpenVPN %s (%s) (%s)\n"
"\n"
"Starting download (~1.8 MB) from:\n"
"'%s'\n"
"to\n"
"'%s'\n"
"\n"
"Please wait..."
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4700
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4766
msgid "Setup: openVPN"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4726
msgid ""
"Invalid File hash: %s !\n"
"localhash = '%s'\n"
"but should be = '%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4730
msgid "Failed remove file: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4766
msgid ""
"OpenVPN not found!\n"
"\n"
"Please select openvpn.exe on next window!\n"
"\n"
"If you did not install openVPN yet: click cancel on next window!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4767
msgid "Select openvpn.exe or Cancel to install openVPN"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4814
msgid ""
"WARNING! Failed to verify files in\n"
"'%s'\n"
"\n"
"Uninstall openVPN and restart oVPN Client Software!\n"
"\n"
"Or install openVPN from URL:\n"
"%s[debug self.LAST_FAILED_CHECKFILE = '%s']"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4819
msgid "Could not detect openVPN Version!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4843
msgid "Could not find openVPN"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4867
msgid "Invalid Hash: '%s'! is '%s' != '%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4870
msgid "Invalid content '%s' in '%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4887
msgid "arch '%s' not supported!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5088
msgid "Quit oVPN.to Client"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5092
msgid "Do you really want to quit?"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5158
msgid "Firewall Settings"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5162
msgid ""
"Restore previous firewall settings?\n"
"\n"
"Press 'YES' to restore your previous firewall settings!\n"
"Press 'NO' to set profiles to 'blockinbound,blockoutbound'!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5165
msgid ""
"Allow outgoing connection to internet?\n"
"\n"
"Press 'YES' to set profiles to 'blockinbound,allowoutbound'!\n"
"Press 'NO' to set profiles to 'blockinbound,blockoutbound'!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5218
msgid "Error"
msgstr ""

